import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Fathom from '@/components/fathom';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL as string;
export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  alternates: {
    canonical: '/'
  },
  title: {
    template: '%s | SafePeek',
    default: 'SafePeek'
  },
  description: 'Enhance Discord with secure link previews, metadata insights, and safety checks.',
  openGraph: {
    images: `${BASE_URL}/og.png`
  }
};

export const viewport: Viewport = {
  themeColor: '#74B9FF'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Fathom />
      <body className={inter.className}>
        {/**
         * This code was generated by v0 by Vercel.
         * @see https://v0.dev/t/c7klMEF3AqV
         */}
        <div className="flex flex-col min-h-screen">
          <header className="py-10 bg-primary dark:bg-[#201d1d]">
            <div className="container flex flex-col items-center gap-2 px-4 md:gap-4 md:flex-row md:px-6 lg:gap-6">
              <Link href="/">
                <div className="flex items-center space-x-2 text-center">
                  <Image alt="SafePeek Logo" className="overflow-hidden" height="80" src="/safepeek.svg" width="80" />
                  <h1 className="text-2xl font-bold tracking-tighter sm:text-4xl text-white">SafePeek</h1>
                </div>
              </Link>
              <div className="mx-auto max-w-3xl text-center md:ml-auto md:text-left lg:px-4">
                <p className="text-sm text-gray-50 md:text-base dark:text-gray-400">
                  Enhance Discord with secure link previews, metadata insights, and safety checks.
                </p>
              </div>
            </div>
          </header>
          {children}
          <footer className="border-t py-12">
            <div className="container flex flex-col gap-4 px-4 md:flex-row md:items-center md:justify-between md:gap-6 md:px-6">
              <nav className="flex items-center gap-4 text-sm md:gap-8">
                <Link className="font-medium text-gray-500 hover:text-gray-700" href="/legal/terms">
                  Terms
                </Link>
                <Link className="font-medium text-gray-500 hover:text-gray-700" href="/legal/privacy">
                  Privacy
                </Link>
                <Link className="font-medium text-gray-500 hover:text-gray-700" href="#">
                  Cookies
                </Link>
              </nav>
              <div className="text-sm text-gray-500">© 2024 Anthony Collier. All rights reserved.</div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
