/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/c7klMEF3AqV
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import {SVGProps} from "react";
import Image from "next/image";

export default function Home() {
  return (
      <div className="flex flex-col min-h-screen">
        <header className="py-10 bg-[#3871c1] dark:bg-[#201d1d]">
          <div className="container flex flex-col items-center gap-2 px-4 md:gap-4 md:flex-row md:px-6 lg:gap-6">
            <div className="flex items-center space-x-2 text-center">
              <Image
                  alt="SafePeek Logo"
                  className="rounded-full overflow-hidden aspect-square"
                  height="80"
                  src="/safepeek.svg"
                  width="80"
              />
              <h1 className="text-2xl font-bold tracking-tighter sm:text-4xl text-white">SafePeek</h1>
            </div>
            <div className="mx-auto max-w-3xl text-center md:ml-auto md:text-left lg:px-4">
              <p className="text-sm text-gray-50 md:text-base dark:text-gray-400">
                Enhance Discord with secure link previews, metadata insights, and safety checks.
              </p>
            </div>
          </div>
        </header>
        <main className="flex-1">
          <div className="container grid max-w-6xl items-center gap-12 px-4 py-12 md:py-16 md:gap-20 md:px-6 lg:grid-cols-2 lg:gap-24">
            <div className="space-y-4 text-center md:space-y-6 md:text-left">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-4xl/line-tight lg:text-5xl/line-tight justify">
                Secure Link Previews
              </h2>
              <p className="text-gray-600 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Beautiful link previews without compromising security. Let your community safely peek at shared links.
              </p>
            </div>
            <div className="flex items-center justify-center">
              <LinkIcon className="w-48 h-48" />
            </div>
            <div className="flex items-center justify-center">
              <InfoIcon className="w-48 h-48" />
            </div>
            <div className="space-y-4 text-center md:space-y-6 md:text-left">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-4xl/line-tight lg:text-5xl/line-tight justify">
                Metadata Insights
              </h2>
              <p className="text-gray-600 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Uncover the story behind links with rich metadata. Know what&apos;s behind the URL before you click.
              </p>
            </div>
            <div className="flex items-center justify-center">
              <CheckIcon className="w-48 h-48" />
            </div>
            <div className="space-y-4 text-center md:space-y-6 md:text-left">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-4xl/line-tight lg:text-5xl/line-tight justify">
                Safety Checks
              </h2>
              <p className="text-gray-600 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Let SafePeek be your guide to the web. We&apos;ll scan links for potential threats so you can browse with
                confidence.
              </p>
            </div>
          </div>
          <div className="bg-gray-100 py-12 dark:bg-gray-800">
            <div className="container flex flex-col items-center justify-center gap-4 px-4 md:flex-row md:gap-10 md:px-6">
              <div className="space-y-3 text-center md:space-y-4 md:text-left">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl text-gray-100">
                  Ready to level up your Discord experience?
                </h2>
                <p className="max-w-[600px] text-gray-100/relaxed dark:text-gray-400">
                  Sign up to be the first to access SafePeek and unlock secure link previews, metadata insights, and
                  safety checks for your Discord server.
                </p>
              </div>
              <form className="flex flex-col gap-4 md:gap-6 min-[300px]:flex-row">
                <Input className="max-w-xs w-full md:max-w-sm" placeholder="Enter your email" type="email" disabled />
                <Button className="w-full md:w-auto bg-[#3871c1] text-white hover:bg-blue-700" type="submit" disabled>
                  Sign up
                </Button>
              </form>
            </div>
          </div>
        </main>
        <footer className="border-t py-12">
          <div className="container flex flex-col gap-4 px-4 md:flex-row md:items-center md:justify-between md:gap-6 md:px-6">
            <nav className="flex items-center gap-4 text-sm md:gap-8">
              <Link className="font-medium text-gray-500 hover:text-gray-700" href="#">
                Terms
              </Link>
              <Link className="font-medium text-gray-500 hover:text-gray-700" href="#">
                Privacy
              </Link>
              <Link className="font-medium text-gray-500 hover:text-gray-700" href="#">
                Cookies
              </Link>
            </nav>
            <div className="text-sm text-gray-500">© 2024 SafePeek. All rights reserved.</div>
          </div>
        </footer>
      </div>
  )
}


function LinkIcon(props: SVGProps<never>) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
        <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
      </svg>
  )
}


function InfoIcon(props: SVGProps<never>) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="10" />
        <path d="M12 16v-4" />
        <path d="M12 8h.01" />
      </svg>
  )
}


function CheckIcon(props: SVGProps<never>) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <polyline points="20 6 9 17 4 12" />
      </svg>
  )
}
